require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/test2s", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Test2. As you add validations to Test2, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the headers
  # in order to pass any filters (e.g. authentication) defined in
  # Test2sController, or in your router and rack
  # middleware. Be sure to keep this updated too.
  let(:valid_headers) {
    {}
  }

  describe "GET /index" do
    it "renders a successful response" do
      Test2.create! valid_attributes
      get test2s_url, headers: valid_headers, as: :json
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      test2 = Test2.create! valid_attributes
      get test2_url(test2), as: :json
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Test2" do
        expect {
          post test2s_url,
               params: { test2: valid_attributes }, headers: valid_headers, as: :json
        }.to change(Test2, :count).by(1)
      end

      it "renders a JSON response with the new test2" do
        post test2s_url,
             params: { test2: valid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:created)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Test2" do
        expect {
          post test2s_url,
               params: { test2: invalid_attributes }, as: :json
        }.to change(Test2, :count).by(0)
      end

      it "renders a JSON response with errors for the new test2" do
        post test2s_url,
             params: { test2: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to eq("application/json")
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested test2" do
        test2 = Test2.create! valid_attributes
        patch test2_url(test2),
              params: { test2: new_attributes }, headers: valid_headers, as: :json
        test2.reload
        skip("Add assertions for updated state")
      end

      it "renders a JSON response with the test2" do
        test2 = Test2.create! valid_attributes
        patch test2_url(test2),
              params: { test2: new_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:ok)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "renders a JSON response with errors for the test2" do
        test2 = Test2.create! valid_attributes
        patch test2_url(test2),
              params: { test2: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to eq("application/json")
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested test2" do
      test2 = Test2.create! valid_attributes
      expect {
        delete test2_url(test2), headers: valid_headers, as: :json
      }.to change(Test2, :count).by(-1)
    end
  end
end
